// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6688.RobotTest.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc6688.RobotTest.Robot;
import org.usfirst.frc6688.RobotTest.subsystems.Door;

/**
 *
 */
public class IncrementOpen extends Command {

    public IncrementOpen() {

        requires(Robot.door);
        double incrementTime = Robot.door.incrementRunTimeOpen;
        setTimeout(incrementTime); 
    }

    protected void initialize() {
    	Robot.door.DoorOpen();
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return isTimedOut();
    }

    protected void end() {
    	Robot.door.Doorstop();
    }

    protected void interrupted() {
    	end();
    }
}
