// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6688.RobotTest.subsystems;

import org.usfirst.frc6688.RobotTest.RobotMap;
import org.usfirst.frc6688.RobotTest.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Door extends Subsystem {


    private final SpeedController frontMotorRight = RobotMap.doorfrontMotorRight;
    private final SpeedController frontMotorLeft = RobotMap.doorfrontMotorLeft;
    public double doorSpeed = 1.0;
    public double incrementRunTimeOpen = 0.9;
    public double incrementRunTimeClose = 0.7;
    //Joystick joystick2= new Joystick (1);

    public void initDefaultCommand() {
 
    }

    public void DoorOpen()
    {
    	frontMotorRight.set(doorSpeed);	
    	frontMotorLeft.set(-doorSpeed);	
    }
    
    public void Doorclose()
    {
    	frontMotorRight.set(-doorSpeed);
    	frontMotorLeft.set(doorSpeed);	
    }
    
    public void Doorstop()
    {
    	frontMotorRight.set(0);
    	frontMotorLeft.set(0);	
    }
}

