// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc6688.RobotTest.subsystems;

import org.usfirst.frc6688.RobotTest.RobotMap;
import org.usfirst.frc6688.RobotTest.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    private final SpeedController frontRight = RobotMap.driveTrainfrontRight;
    private final SpeedController frontLeft = RobotMap.driveTrainfrontLeft;
    private final SpeedController rearRight = RobotMap.driveTrainrearRight;
    private final SpeedController rearLeft = RobotMap.driveTrainrearLeft;
    private final RobotDrive robotDrive41 = RobotMap.driveTrainRobotDrive41;

    private double autoSpeed= 0.3;
    private double turnSpeedSlow=0.2;
    private double turnSpeedFast=0.5;
    public double timeRunForward=2.0;
    public double timeRunBackwards=1.0;
    Joystick stick = new Joystick(0);
    

    public void initDefaultCommand() {
    	setDefaultCommand(new DriveWithJoysticks());
    }
    
    public void driveWithJoysticks(double leftJoystick, double RightJoystick)
    {
    	robotDrive41.arcadeDrive(stick);
    }
    
    public void driveForward()
    {
    	robotDrive41.arcadeDrive(autoSpeed, autoSpeed);
    }
    
    public void driveBackwards()
    {
    	robotDrive41.arcadeDrive(-autoSpeed, -autoSpeed);
    }
    public void turnLeft()
    {
    	robotDrive41.arcadeDrive(turnSpeedSlow, turnSpeedFast);
    }
    public void turnRight()
    {
    	robotDrive41.arcadeDrive(turnSpeedFast, turnSpeedSlow);
    }
    public void stop()
    {
    	robotDrive41.arcadeDrive(0.0, 0.0);
    }
}

